name: Build, Pack & Push Nuget Package Manual
on:
  workflow_dispatch:
    inputs:
      package-version-text:
        description: 'Package Version'
        required: true
        type: string
env:
  packageName: 'RB.SharedKernel'
  artifactPath: '/home/runner/work/RB.SharedKernel'
jobs:
  get-version:
    name: Set Workflow Variables
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.package-variables.outputs.package-version }}
      version: ${{ steps.package-variables.outputs.version }}
      version-suffix: ${{ steps.package-variables.outputs.version-suffix }}
    steps:
      - name: Print Package Version
        shell: pwsh
        run: |
          echo "${{ github.event.inputs.package-version-text }}"
      - name: Validate Package Version
        shell: pwsh
        run: |
          echo "Validate Package Version"
            if ("${{ github.event.inputs.package-version-text }}" -notmatch '^v\d+\.\d+\.\d+(-\w+(\.\d+)*)?$')
          {
            echo "Invalid package version format. The package version must be in the format v1.0.0 or v1.0.0-suffix"
            exit 1
          }
          else 
          {
            echo "Valid package version format"
          }
      - id: package-variables
        name: Set Package Variables
        shell: pwsh
        run: |
          $packageVersionText = "${{ github.event.inputs.package-version-text }}";
          $packageVersion = $packageVersionText.split('v')[1];
          echo "package-version=$packageVersion" >> $env:GITHUB_OUTPUT
          $packageVersionArray = $packageVersion.split('-');
          $version = $packageVersionArray[0];
          echo "version=$version" >> $env:GITHUB_OUTPUT
          $versionSuffix = $packageVersionArray[1];
          echo "version-suffix=$versionSuffix" >> $env:GITHUB_OUTPUT
  build_package:
    name: Build
    runs-on: ubuntu-latest
    needs: get-version
    steps:
      - name: Print Variables
        run: |
          echo "${{ github.event.inputs.package-version-text }}"
          echo "${{ needs.get-version.outputs.package-version }}"
          echo "${{ needs.get-version.outputs.version }}"
          echo "${{ needs.get-version.outputs.version-suffix }}"
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            8.0.x
            9.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Publish
        run: dotnet publish --configuration Release --output ${{ env.artifactPath }}/publish/release/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.packageName }}.${{ needs.get-version.outputs.package-version}}
          path: ${{ env.artifactPath }}/publish/release/
          overwrite: true

  pack_push_package:
    name: Pack & Push
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - name: Pack
        run: dotnet pack --no-build --no-restore ${{ env.artifactPath }}/publish/release/ -p:PackageVersion=${{ needs.get-version.outputs.package-version }} --version-suffix ${{ needs.get-version.outputs.version-suffix }} --artifacts-path ${{ env.artifactPath }}/publish/nuget/ --configuration Release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.packageName }}.${{ needs.get-version.outputs.package-version}}
          path: ${{ env.artifactPath }}/publish/release/
          overwrite: true
      - name: Push
        run: dotnet nuget push ${{ env.artifactPath }}/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}