name: Build, Pack & Push Nuget Package Manual
on:
  workflow_dispatch:
    inputs:
      package-version-text:
        description: 'Package Version'
        required: true
        type: string
env:
  packageName: 'RB.SharedKernel'
  artifactPath: '/home/runner/work/RB.SharedKernel'
jobs:
  get-version:
    name: Set Workflow Variables
    runs-on: ubuntu-latest
    # outputs:
      # package-version: ${{ steps.variables.outputs.package-version }}
      # version: ${{ steps.variables.outputs.version }}
      # version-suffix: ${{ steps.variables.outputs.version-suffix }}
    steps:
      - name: Print Package Version
        shell: pwsh
        run: |
          echo "${{ github.event.inputs.package-version-text }}"
      

